packages:
    - 'packages/*'
allowBuilds:
    '@parcel/watcher': false
    esbuild: false
    ttf2woff2: false
catalog:
    typescript: ^7.0.2
    vite: npm:@voidzero-dev/vite-plus-core@0.2.5
    vite-plus: 0.2.7
    '@vitest/coverage-v8': 4.1.10

configDependencies:
    '@pnpm/pacquet': 0.11.12

minimumReleaseAgeExclude:
    - '@typescript/typescript-aix-ppc64@7.0.2'
    - '@typescript/typescript-darwin-arm64@7.0.2'
    - '@typescript/typescript-darwin-x64@7.0.2'
    - '@typescript/typescript-freebsd-arm64@7.0.2'
    - '@typescript/typescript-freebsd-x64@7.0.2'
    - '@typescript/typescript-linux-arm64@7.0.2'
    - '@typescript/typescript-linux-arm@7.0.2'
    - '@typescript/typescript-linux-loong64@7.0.2'
    - '@typescript/typescript-linux-mips64el@7.0.2'
    - '@typescript/typescript-linux-ppc64@7.0.2'
    - '@typescript/typescript-linux-riscv64@7.0.2'
    - '@typescript/typescript-linux-s390x@7.0.2'
    - '@typescript/typescript-linux-x64@7.0.2'
    - '@typescript/typescript-netbsd-arm64@7.0.2'
    - '@typescript/typescript-netbsd-x64@7.0.2'
    - '@typescript/typescript-openbsd-arm64@7.0.2'
    - '@typescript/typescript-openbsd-x64@7.0.2'
    - '@typescript/typescript-sunos-x64@7.0.2'
    - '@typescript/typescript-win32-arm64@7.0.2'
    - '@typescript/typescript-win32-x64@7.0.2'
    - '@voidzero-dev/vite-plus-core@0.2.5'
    - '@voidzero-dev/vite-plus-darwin-arm64@0.2.5'
    - '@voidzero-dev/vite-plus-darwin-x64@0.2.5'
    - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.5'
    - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.5'
    - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.5'
    - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.5'
    - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.5'
    - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.5'
    - typescript@7.0.2
    - vite-plus@0.2.5

overrides:
    lodash@>=4.0.0 <=4.17.22: '^4.18.1'
    make-fetch-happen: 16.0.1
    minimatch@<3.1.4: '^10.0.0'
    underscore@<=1.13.7: '^1.13.8'
    vite: 'catalog:'
    vitepress>vite: ^8.0.0
peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'
        vitest: '*'
