packages:
    - 'packages/*'
allowBuilds:
    '@parcel/watcher': false
    esbuild: false
    ttf2woff2: false
catalog:
    typescript: ^6.0.3
    vite: npm:@voidzero-dev/vite-plus-core@0.2.1
    vite-plus: 0.2.1
    '@vitest/coverage-v8': 4.1.9

configDependencies:
    '@pnpm/pacquet': 0.11.10

minimumReleaseAgeExclude:
    - '@voidzero-dev/vite-plus-core@0.2.1'
    - '@voidzero-dev/vite-plus-darwin-arm64@0.2.1'
    - '@voidzero-dev/vite-plus-darwin-x64@0.2.1'
    - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.1'
    - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.1'
    - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.1'
    - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.1'
    - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.1'
    - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.1'
    - vite-plus@0.2.1

overrides:
    brace-expansion@>=1.0.0 <=1.1.11: '^1.1.12'
    lodash@>=4.0.0 <=4.17.22: '^4.17.23'
    make-fetch-happen: 16.0.1
    minimatch@<3.1.4: '^10.0.0'
    underscore@<=1.13.7: '^1.13.8'
    vite: 'catalog:'
    vitepress>vite: ^8.0.0
peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'
        vitest: '*'
