/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GenerateWebfontsResult {
  get eot(): Uint8Array | null
  get svg(): string | null
  get ttf(): Uint8Array | null
  get woff2(): Uint8Array | null
  get woff(): Uint8Array | null
  generateCss(urls?: Partial<Record<FontType, string>>): string
  generateHtml(urls?: Partial<Record<FontType, string>>): string
}

/**
 * Guaranteed fields supplied to a `cssContext` callback. Additional keys from
 * user-supplied `templateOptions` are merged into the same object at runtime,
 * so the JS-side type widens this with an open-ended index signature.
 */
export interface CssContext {
  /** Name of the generated font, mirroring the `fontName` option. */
  fontName: string
  /**
   * Pre-rendered value for the CSS `@font-face` `src:` descriptor — a
   * comma-separated list of `url(...) format(...)` entries derived from the
   * configured `types`, `order`, and `cssFontsUrl`.
   */
  src: string
  /**
   * Map from glyph name to its assigned codepoint as a hex-encoded string
   * (e.g. `"add" -> "f101"`), suitable for use inside CSS `content`
   * declarations like `content: "\f101"`.
   */
  codepoints: Record<string, string>
}

export declare const enum FontType {
  Svg = 'svg',
  Ttf = 'ttf',
  Eot = 'eot',
  Woff = 'woff',
  Woff2 = 'woff2'
}

export interface FormatOptions {
  svg?: SvgFormatOptions
  ttf?: TtfFormatOptions
  woff?: WoffFormatOptions
}

export declare function generateWebfonts(options: GenerateWebfontsOptions, rename?: (((arg: string) => string)) | undefined | null, cssContext?: (((arg: Record<string, any>) => Record<string, any>)) | undefined | null, htmlContext?: (((arg: Record<string, any>) => Record<string, any>)) | undefined | null): Promise<GenerateWebfontsResult>

export interface GenerateWebfontsOptions {
  ascent?: number
  centerHorizontally?: boolean
  centerVertically?: boolean
  css?: boolean
  cssDest?: string
  cssTemplate?: string
  codepoints?: Record<string, number>
  cssFontsUrl?: string
  descent?: number
  dest: string
  files: Array<string>
  fixedWidth?: boolean
  formatOptions?: FormatOptions
  html?: boolean
  htmlDest?: string
  htmlTemplate?: string
  fontHeight?: number
  fontName?: string
  fontStyle?: string
  fontWeight?: string
  ligature?: boolean
  normalize?: boolean
  order?: Array<FontType>
  optimizeOutput?: boolean
  preserveAspectRatio?: boolean
  round?: number
  startCodepoint?: number
  templateOptions?: Record<string, any>
  types?: Array<FontType>
  writeFiles?: boolean
}

/**
 * Guaranteed fields supplied to an `htmlContext` callback. Additional keys
 * from user-supplied `templateOptions` are merged into the same object at
 * runtime, so the JS-side type widens this with an open-ended index signature.
 */
export interface HtmlContext {
  /** Name of the generated font, mirroring the `fontName` option. */
  fontName: string
  /**
   * Glyph names in declaration order, after any `rename` callback has been
   * applied. Useful for iterating over icons in a preview template.
   */
  names: Array<string>
  /**
   * Pre-rendered CSS (the same string the engine writes to the `.css`
   * output) so HTML templates can embed it inline for self-contained
   * previews without an external stylesheet reference.
   */
  styles: string
  /**
   * Map from glyph name to its assigned codepoint as a numeric value
   * (e.g. `"add" -> 0xF101`). Use the CSS context's hex form if you need a
   * string for embedding into CSS `content` declarations.
   */
  codepoints: Record<string, number>
}

export interface SvgFormatOptions {
  centerVertically?: boolean
  fontId?: string
  metadata?: string
  optimizeOutput?: boolean
  preserveAspectRatio?: boolean
}

export interface TtfFormatOptions {
  copyright?: string
  description?: string
  ts?: number
  url?: string
  version?: string
}

export interface WoffFormatOptions {
  metadata?: string
}
