/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GenerateWebfontsResult {
  get eot(): Uint8Array | null
  get svg(): string | null
  get ttf(): Uint8Array | null
  get woff2(): Uint8Array | null
  get woff(): Uint8Array | null
  generateCss(urls?: Partial<Record<FontType, string>>): string
  generateHtml(urls?: Partial<Record<FontType, string>>): string
}

export declare const enum FontType {
  Svg = 'svg',
  Ttf = 'ttf',
  Eot = 'eot',
  Woff = 'woff',
  Woff2 = 'woff2'
}

export interface FormatOptions {
  svg?: SvgFormatOptions
  ttf?: TtfFormatOptions
  woff?: WoffFormatOptions
}

export declare function generateWebfonts(options: GenerateWebfontsOptions, rename?: (((arg: string) => string)) | undefined | null, cssContext?: (((arg: Record<string, any>) => Record<string, any>)) | undefined | null, htmlContext?: (((arg: Record<string, any>) => Record<string, any>)) | undefined | null): Promise<GenerateWebfontsResult>

export interface GenerateWebfontsOptions {
  ascent?: number
  centerHorizontally?: boolean
  centerVertically?: boolean
  css?: boolean
  cssDest?: string
  cssTemplate?: string
  codepoints?: Record<string, number>
  cssFontsUrl?: string
  descent?: number
  dest: string
  files: Array<string>
  fixedWidth?: boolean
  formatOptions?: FormatOptions
  html?: boolean
  htmlDest?: string
  htmlTemplate?: string
  fontHeight?: number
  fontName?: string
  fontStyle?: string
  fontWeight?: string
  ligature?: boolean
  normalize?: boolean
  order?: Array<FontType>
  optimizeOutput?: boolean
  preserveAspectRatio?: boolean
  round?: number
  startCodepoint?: number
  templateOptions?: Record<string, any>
  types?: Array<FontType>
  writeFiles?: boolean
}

export interface SvgFormatOptions {
  centerVertically?: boolean
  fontId?: string
  metadata?: string
  optimizeOutput?: boolean
  preserveAspectRatio?: boolean
}

export interface TtfFormatOptions {
  copyright?: string
  description?: string
  ts?: number
  url?: string
  version?: string
}

export interface WoffFormatOptions {
  metadata?: string
}
