/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GenerateWebfontsResult {
  get eot(): Uint8Array | null
  get svg(): string | null
  get ttf(): Uint8Array | null
  get woff2(): Uint8Array | null
  get woff(): Uint8Array | null
  generateCss(urls?: Partial<Record<FontType, string>>): string
  generateHtml(urls?: Partial<Record<FontType, string>>): string
}

/**
 * Guaranteed fields supplied to a `cssContext` callback. Additional keys from
 * user-supplied `templateOptions` are merged into the same object at runtime,
 * so the JS-side type widens this with an open-ended index signature.
 */
export interface CssContext {
  /** Name of the generated font, mirroring the `fontName` option. */
  fontName: string
  /**
   * Pre-rendered value for the CSS `@font-face` `src:` descriptor — a
   * comma-separated list of `url(...) format(...)` entries derived from the
   * configured `types`, `order`, and `cssFontsUrl`.
   */
  src: string
  /**
   * Map from glyph name to its assigned codepoint as a hex-encoded string
   * (e.g. `"add" -> "f101"`), suitable for use inside CSS `content`
   * declarations like `content: "\f101"`.
   */
  codepoints: Record<string, string>
}

export declare const enum FontType {
  Svg = 'svg',
  Ttf = 'ttf',
  Eot = 'eot',
  Woff = 'woff',
  Woff2 = 'woff2'
}

/**
 * Per-format configuration object. Each field carries options that only apply
 * to the corresponding output format.
 */
export interface FormatOptions {
  /** SVG-format options. */
  svg?: SvgFormatOptions
  /** TTF-format options. */
  ttf?: TtfFormatOptions
  /** WOFF1-format options. (WOFF2 has no format-specific options.) */
  woff?: WoffFormatOptions
}

export declare function generateWebfonts(options: GenerateWebfontsOptions, rename?: (((arg: string) => string)) | undefined | null, cssContext?: (((arg: Record<string, any>) => Record<string, any>)) | undefined | null, htmlContext?: (((arg: Record<string, any>) => Record<string, any>)) | undefined | null): Promise<GenerateWebfontsResult>

export interface GenerateWebfontsOptions {
  ascent?: number
  centerHorizontally?: boolean
  centerVertically?: boolean
  css?: boolean
  cssDest?: string
  cssTemplate?: string
  codepoints?: Record<string, number>
  cssFontsUrl?: string
  descent?: number
  dest: string
  files: Array<string>
  fixedWidth?: boolean
  formatOptions?: FormatOptions
  html?: boolean
  htmlDest?: string
  htmlTemplate?: string
  fontHeight?: number
  fontName?: string
  fontStyle?: string
  fontWeight?: string
  ligature?: boolean
  normalize?: boolean
  order?: Array<FontType>
  optimizeOutput?: boolean
  preserveAspectRatio?: boolean
  round?: number
  startCodepoint?: number
  templateOptions?: Record<string, any>
  types?: Array<FontType>
  writeFiles?: boolean
}

/**
 * Guaranteed fields supplied to an `htmlContext` callback. Additional keys
 * from user-supplied `templateOptions` are merged into the same object at
 * runtime, so the JS-side type widens this with an open-ended index signature.
 */
export interface HtmlContext {
  /** Name of the generated font, mirroring the `fontName` option. */
  fontName: string
  /**
   * Glyph names in declaration order, after any `rename` callback has been
   * applied. Useful for iterating over icons in a preview template.
   */
  names: Array<string>
  /**
   * Pre-rendered CSS (the same string the engine writes to the `.css`
   * output) so HTML templates can embed it inline for self-contained
   * previews without an external stylesheet reference.
   */
  styles: string
  /**
   * Map from glyph name to its assigned codepoint as a numeric value
   * (e.g. `"add" -> 0xF101`). Use the CSS context's hex form if you need a
   * string for embedding into CSS `content` declarations.
   */
  codepoints: Record<string, number>
}

/**
 * SVG-format–specific options for the intermediate SVG font and the per-glyph
 * path processing that feeds every other format.
 */
export interface SvgFormatOptions {
  /**
   * SVG-format override of the top-level `centerVertically` option. When set,
   * it wins over the top-level value; centers each glyph vertically inside
   * the em-square based on its bounding box.
   */
  centerVertically?: boolean
  /**
   * Value of the SVG font's `id` attribute. Defaults to `fontName` when
   * omitted.
   */
  fontId?: string
  /** Content embedded inside the generated SVG font's `<metadata>` element. */
  metadata?: string
  /**
   * SVG-format override of the top-level `optimizeOutput` option. When set,
   * it wins over the top-level value; runs an SVG path optimizer over each
   * glyph, trading a small amount of build time for smaller output bytes.
   */
  optimizeOutput?: boolean
  /**
   * SVG-format override of the top-level `preserveAspectRatio` option. When
   * set, it wins over the top-level value; preserves the source viewBox
   * aspect ratio when scaling glyphs into the em-square.
   */
  preserveAspectRatio?: boolean
}

/**
 * TTF-format–specific options. Populates fields in the generated TTF `name`
 * and `head` tables.
 */
export interface TtfFormatOptions {
  /** Copyright string written to the TTF `name` table (record id 0). */
  copyright?: string
  /** Description string written to the TTF `name` table (record id 10). */
  description?: string
  /**
   * Unix timestamp in seconds used for the `created` and `modified` fields
   * in the TTF `head` table. Pin to a fixed value to produce byte-stable
   * reproducible builds.
   */
  ts?: number
  /** Manufacturer URL written to the TTF `name` table (record id 11). */
  url?: string
  /** Version string written to the TTF `name` table (record id 5). */
  version?: string
}

/** WOFF-format–specific options. Affects only WOFF1 output; WOFF2 ignores these. */
export interface WoffFormatOptions {
  /** XML string embedded in the WOFF1 metadata block. */
  metadata?: string
}
