import type { GeneratedFontTypes } from '@vusion/webfonts-generator';

/**
 * Represents a webfont generated by the plugin, containing its type and the URL to access it.
 */
export interface GeneratedWebfont {
    /** The type of the generated webfont. */
    type: GeneratedFontTypes;
    /** The file URL to access the generated webfont. */
    href: string;
}
