name: Docs

on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        name: build docs
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: setup pages
              uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
            - uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754 # v1.18.0
              with:
                  node-version-file: .node-version
                  run-install: true
                  cache: true
            - name: build docs
              run: vp run @atlowchemi/vite-svg-webfont-docs#build
            - name: upload pages artifact
              uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
              with:
                  path: packages/docs/.vitepress/dist

    deploy:
        name: deploy docs
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: deploy to github pages
              id: deployment
              uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
