name: CI

on:
    push:
        branches:
            - 'main'
    pull_request:

permissions:
    contents: read

jobs:
    ci:
        name: run CI
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - uses: voidzero-dev/setup-vp@v1
              with:
                  node-version-file: .nvmrc
                  run-install: true
                  cache: true
            - run: vp check

    test:
        name: run test
        needs: [ci]
        strategy:
            matrix:
                node_version: [20.x, 22.x, 24.x, 25.x]
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - uses: voidzero-dev/setup-vp@v1
              with:
                  node-version-file: .nvmrc
                  run-install: true
                  cache: true
            - name: run coverage test
              run: vp run coverage
            - uses: actions/upload-artifact@v7
              with:
                  name: coverage-${{ matrix.node_version }}
                  path: coverage
