name: automatic release

on:
    push:
        tags:
            - v*

permissions:
    contents: read
    id-token: write

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v6
            - name: Install pnpm
              uses: pnpm/action-setup@v5
            - name: setup Node
              uses: actions/setup-node@v6
              with:
                  node-version-file: .nvmrc
                  cache: 'pnpm'
                  registry-url: 'https://registry.npmjs.org'
            - name: frozen install
              run: pnpm i --frozen-lockfile --prefer-offline
            - name: build
              run: node --run build
            - name: deploy
              run: pnpm publish --provenance
